// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUzebyRy1OZtMNewEgk5Xy_pcutpzGgjg',
    appId: '1:904397598574:web:17bcc77c1358d15f251b7f',
    messagingSenderId: '904397598574',
    projectId: 'projeto-final-a01dc',
    authDomain: 'projeto-final-a01dc.firebaseapp.com',
    storageBucket: 'projeto-final-a01dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwUbIQrScNVoK_BMtzy7RS4bVYWk5D048',
    appId: '1:904397598574:android:825689268b13504d251b7f',
    messagingSenderId: '904397598574',
    projectId: 'projeto-final-a01dc',
    storageBucket: 'projeto-final-a01dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAk8S_80sEclBaHhSI9s50UYm0FcUQ8Da0',
    appId: '1:904397598574:ios:1fa24d7d59339d1d251b7f',
    messagingSenderId: '904397598574',
    projectId: 'projeto-final-a01dc',
    storageBucket: 'projeto-final-a01dc.appspot.com',
    iosClientId: '904397598574-g3t6vjehpsp2q6hs46ssrs8l574023oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.meuapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAk8S_80sEclBaHhSI9s50UYm0FcUQ8Da0',
    appId: '1:904397598574:ios:1fa24d7d59339d1d251b7f',
    messagingSenderId: '904397598574',
    projectId: 'projeto-final-a01dc',
    storageBucket: 'projeto-final-a01dc.appspot.com',
    iosClientId: '904397598574-g3t6vjehpsp2q6hs46ssrs8l574023oc.apps.googleusercontent.com',
    iosBundleId: 'com.example.meuapp',
  );
}
